### ISSUE TITLE
I'm interested in taking over maintenance of the project

### ISSUE THREAD

**Issue by me4502** [me4502/gatsby-plugin-react-helmet-async#91]
Hi,

I noticed the README states that you're no longer interested in maintaining this. I'd be interested in maintaining this, as I'm using this on one site atm and plan on using it for more - and I generally run on latest versions of everything so will have the motivation to keep this up to date.

I have a strong knowledge of React, Gatsby, TS etc as I've been working heavily with all of these technologies for at least 3 years

**Comment by MartinRosenberg** [comment]
Hi there, @me4502! I just want to make sure you're still truly interested inGatsby because I saw your public Gatsby-related activity dropped off a lot after 2019, and I'd feel bad if it ended up forgotten like it has been by me; and double-checking you're still interested because I'm a bit late replying (as I was without a dev machine for a couple months). If that's a yes to both of those, I'll go ahead and transfer it to you! 😃

**Comment by me4502** [comment]
Hi, yeah I'm still interested - My main reason for dropping off public Gatsby work a lot was that I was only making PRs when I needed things fixed/changed, and that stopped being as much of the case after then.

**Comment by MartinRosenberg** [comment]
Sounds good. GitHub does require you to delete (or rename) your fork before I can transfer ownership to you, as well.

**Comment by me4502** [comment]
Thanks, I just renamed it as I have an open PR that I'm not sure what would happen to if I deleted it

**Comment by MartinRosenberg** [comment]
This time it told me that "me4502 already has a repository in the MartinRosenberg/gatsby-plugin-react-helmet-async network". So apparently you have to delete it after all. Seeing that this is about to be your repository anyway, I just went ahead and merged the PR so you can delete the fork.

**Comment by me4502** [comment]
Thanks, I've just deleted it

**Comment by MartinRosenberg** [comment]
I initiated the transfer. Have fun!

**Comment by me4502** [comment]
Thanks :)

**Comment by me4502** [comment]
@MartinRosenberg Would it be possible to please either transfer the npm package ownership to the `me4502` npm account, or add me to it? Thanks

**Comment by MartinRosenberg** [comment]
I woke up this morning thinking about that. 😅  Just sent you an invite.

**Comment by me4502** [comment]
Thanks :)
